#!/usr/bin/env python
'''

1. Use the split method to divide the 
following IPv6 address into groups of 4 hex digits 
FE80:0000:0000:0000:0105:A3EE:EE1F:1720

2. Use the join method to reunite your split 
IPv6 address back to its original value.

ipv6_addr = "FE80:0000:0000:0000:0105:A3EE:EE1F:1720"

ipv6_split = ipv6_addr.split(:)

print
print "IPv6 address is split as follows - "
print ipv6_split
print

ipv6_new = ":".join(ipv6_split)

print "IPv6 address re-joined:"
print ipv6_new
print
